<script type="text/javascript">
    //<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function (button, url) {
        var obj = document.getElementById("qty");


        if (obj) {
            if (parseInt(obj.value) < 1) {
                alert("Please specify Quantity");
                return false;
            }
        }
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;
            if (url) {
                form.action = url;
            }
            var e = null;
            // Start of our new ajax code
            if (!url) {
                url = jQuery('#product_addtocart_form').attr('action');
            }
            url = url.replace("checkout/cart", "ajaxcart/index");
            url = url.replace("wishlist/index/cart","ajaxcart/index/add");
            var data = jQuery('#product_addtocart_form').serialize();
            showLoading();
            try {
                jQuery.ajax({
                    url: url,
                    dataType: 'json',
                    data: data,
                    success: function (data) {
                        hideLoading();
                        setAjaxData(data);
                    }
                });
            } catch (e) {
                alert(e);
            }

            this.form.action = oldUrl;
            if (e) {
                throw e;
            }
        }
    }.bind(productAddToCartForm);
    function submit() {
        alert("ok");
        jQuery('.btn-cart').bind('click', function () {
            document.forms.submit();
        });
    }
    productAddToCartForm.submitLight = function (button, url) {
        if (this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
    //]]>
</script>